parameters:
    nfg_badges.subscriber.class: NFG\BadgesBundle\Event\BadgesSubscriber

services:
    nfg_badges.subscriber:
        class: "%nfg_badges.subscriber.class%"
        arguments:
            - "@translator"
            - "@doctrine.orm.entity_manager"
            - "@meurs.helper"
        tags:
            - { name: kernel.event_subscriber }
